### ISSUE TITLE
Why use **manual** two tokens lookahead

### ISSUE THREAD

**Issue by bd82** [matthemsteger/df-tools#1]
https://github.com/matthemsteger/df-tools/blob/master/src/dsl/parsers/worldGenParser.js#L38
```javaScript
				GATE() {
					const nextNameToken = this.LA(2);
					return tokenMatcher(nextNameToken, worldGenTokens.WorldGenSettingToken);
				},
```

Chevrotain is an LL(K) parser, should be able to look k (>1) tokens ahead.
What is the edge case requiring a gate here?

**Comment by matthemsteger** [comment]
I went through some iterations there. The basic case I was trying to accomplish was parsing a grammar like this ..

```
[WORLD_GEN]
[SETTING1]
[SETTING2:ARG1]
[SETTING3]
...
[WORLD_GEN]
... repeats
```

I started out by a MANY for the world gen subrules, and then once those tokens are consumed ([, WORLD_GEN, ]) .. then a MANY with a giant OR of the possibilities. The main thing I was struggling with is that I know all the settings that are allowed there, but they can be in any order. I think though that I was pushing that kind of validation to the parsing when I shouldnt have.

I ended up using inheritance as a sort of implicit OR with all the alternatives being subclasses of `WorldGenSettingToken`. I think I did not have that gate at first and what happened was that it would give me an unexpected token on the next WORLD_GEN because that token was not part of the `WorldGenSettingToken` hierarchy.

I commented out the GATE() and ran the integration tests again ..
`DEBUG=df:test:dsl:int-worldGenParser npm run mocha:integration`

```
 df:test:dsl:int-worldGenParser parser is [ { [MismatchedTokenException: Expecting token of type --> WorldGenSettingToken <-- but found --> 'WORLD_GEN' <--]
  df:test:dsl:int-worldGenParser     name: 'MismatchedTokenException',
  df:test:dsl:int-worldGenParser     message: 'Expecting token of type --> WorldGenSettingToken <-- but found --> \'WORLD_GEN\' <--',
  df:test:dsl:int-worldGenParser     token:
  df:test:dsl:int-worldGenParser      { image: 'WORLD_GEN',
  df:test:dsl:int-worldGenParser        startOffset: 2501,
  df:test:dsl:int-worldGenParser        endOffset: 2509,
  df:test:dsl:int-worldGenParser        startLine: 90,
  df:test:dsl:int-worldGenParser        endLine: 90,
  df:test:dsl:int-worldGenParser        startColumn: 2,
  df:test:dsl:int-worldGenParser        endColumn: 10,
  df:test:dsl:int-worldGenParser        tokenType: 826 },
  df:test:dsl:int-worldGenParser     resyncedTokens: [],
  df:test:dsl:int-worldGenParser     context:
  df:test:dsl:int-worldGenParser      { ruleStack:
  df:test:dsl:int-worldGenParser         [ 'parseWorldGenFile',
  df:test:dsl:int-worldGenParser           'worldGenConfiguration',
  df:test:dsl:int-worldGenParser           'worldGenSetting' ],
  df:test:dsl:int-worldGenParser        ruleOccurrenceStack: [ 1, 1, 1 ] } } ] +4ms
```

I think what I expected there was that it would sort of assume that the MANY for the settings had ended, and then check to see if we were starting a MANY for the WORLD_GEN rule.

**Comment by bd82** [comment]
Thanks for the detailed explanation.

This usage of the gate seems to make sense to disambiguate the grammar 
as it effectively **not** context free. 

If we call the **worldGenConfiguration** directly a single "[" should suffice
to identify another iteration. But if we call **worldGenConfiguration** from **parseWorldGenFile**
then we need to check **two** tokens ahead.

The lookahead function of the MANY should not (and cannot!) take into account
the current rule hierarchy, at least not in a **context free** grammar...

* It is also possible to do **negative** lookahead if you ever want to get rid of the token inheritance.
   ```javascript
   !tokenMatcher(nextNameToken, worldGenTokens. WorldGen);
   ```

The runtime behavior (error without the Gate) is fine.
But a little validation by Chevrotain to warn about this could be handy. 
I'm just not sure on the complexity of detecting this edge case yet.
